wandb_project: 'TANGO'
exp_name: 'debug'

wandb_entity: ''
wandb_key: ""
wandb_log_dir: '/content/outputs/wandb'
output_dir: /content/drive/MyDrive/005_Weights/
log_period: 1
seed: 42
resume_from_checkpoint: "" #/content/diffusion_weights/v7_dup_14_continue/checkpoint-245000/'
resume_steps: "" # 245000
# base_model_path: '/content/pretrained_weights/stable-diffusion-v1-5'
# vae_model_path: '/content/pretrained_weights/sd-vae-ft-mse'
# image_encoder_path: '/content/pretrained_weights/image_encoder'
# controlnet_openpose_path: '/content/pretrained_weights/control_v11p_sd15_openpose/diffusion_pytorch_model.bin'
# pose_guider_pretrain: False
# mm_path: './pretrained_models/mm_sd_v15_v2.ckpt'
stage1_ckpt_dir: ""
stage1_ckpt_step: ""

data:
  name_pyfile: "datasets.beat2_v5"
  class_name: "BEAT2Dataset"
  train_bs: 2
  meta_paths:
    - "./datasets/data_json/show-oliver-s40_w128.json"
  # test_meta_paths: "./datasets/data_json/show_oliver_test/Abortion_Laws_-_Last_Week_Tonight_with_John_Oliver_HBO-DRauXXz6t0Y.webm.json"
  "test_meta_paths": "./datasets/data_json/show_oliver_test/Stupid_Watergate_-_Last_Week_Tonight_with_John_Oliver_HBO-FVFdsl29s_Q.mkv.json"
  pose_norm: False
  pose_fps: 30
  rot6d: True
  pose_dims: 825
  pose_length: 128
  stride: 20
  test_length: 128
  audio_sr: 16000
  audio_fps: 16000

model:
  name_pyfile: "models.jointembedding_high_env0"
  class_name: "JointEmbedding"
  motion_f: 256
  audio_rep: wave16k
  audio_sr: 16000
  audio_fps: 16000
  audio_norm: False
  audio_f: 256
  word_rep: textgrid
  word_index_num: 11195
  word_dims: 300
  facial_rep: smplxflame_30
  facial_dims: 100
  facial_norm: False
  facial_f: 0
  f_pre_encoder: null
  f_encoder: null
  f_fix_pre: False
  id_rep: onehot
  speaker_f: 0
  hidden_size: 512
  n_layer: 1
  motion_dim: 825
 
validation:
  val_loss_steps: 1
  validation_steps: 1000
  # guidance_scale: 3.5
  # denoising_steps: 20 

solver:
  gradient_accumulation_steps: 1
  # mixed_precision: 'fp16'
  # enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: False 
  max_train_steps: 5000000
  max_grad_norm: 1.0
  # lr
  learning_rate: 2e-5
  scale_lr: False 
  lr_warmup_steps: 50
  lr_scheduler: 'constant'
  # optimizer
  use_8bit_adam: False 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

# noise_scheduler_kwargs:
#   num_train_timesteps: 1000
#   beta_start:          0.00085
#   beta_end:            0.012
#   beta_schedule:       "linear"
#   steps_offset:        1
#   clip_sample:         false

# guidance_encoder_kwargs:
#   guidance_embedding_channels: 320
#   guidance_input_channels: 3
#   block_out_channels: [16, 32, 96, 256]

# weight_dtype: 'fp16'  # [fp16, fp32]
# uncond_ratio: 0.1
# noise_offset: 0.05
# snr_gamma: 5.0
# enable_zero_snr: True